package org.flippets.app;

import android.content.SharedPreferences;
import android.os.*;
import android.view.*;
import android.view.accessibility.AccessibilityNodeInfo;
import android.widget.*;
import org.json.*;
import java.util.*;

/** Emulator-only real dialog controls, preference isolation, and rendered PAG matrices. */
final class PetLayoutQa {
    private static volatile boolean running;
    private static final String[] KEYS={"petClockless","petClockScale","petClockX","petClockY","petLargeScale","petLargeX","petLargeY"};
    private static final String[] SELECTION_KEYS={"pet","petId","changeRevision"};
    final MainActivity a;final Handler handler=new Handler(Looper.getMainLooper());final JSONArray results=new JSONArray();
    SharedPreferences prefs;Map<String,Object> saved=new HashMap<>(),savedSelection=new HashMap<>();Map<String,?> clean;int savedScene,savedOverrideIndex,failed;String path;long playRevision,savedOverrideUntil;boolean ended,selectionSaved;
    ViewGroup original;PetStage stage;float[] initial,large;long readyDeadline;
    PetLayoutQa(MainActivity a){this.a=a;}
    static void start(MainActivity a){if(!(Build.HARDWARE.contains("ranchu")||Build.HARDWARE.contains("goldfish")))throw new IllegalStateException("PetLayoutQa is emulator-only");if(running)return;running=true;new PetLayoutQa(a).begin();}
    void record(String name,boolean pass,String detail){try{results.put(new JSONObject().put("test",name).put("ok",pass).put("detail",detail));}catch(JSONException ignored){}if(!pass)failed++;}
    void later(Runnable step){handler.postDelayed(()->{if(ended)return;try{if(a.isDestroyed()||!a.preview.running)throw new IllegalStateException("Main/stage stopped during QA");step.run();}catch(Throwable e){record("unexpected_error",false,e.getClass().getSimpleName()+": "+e.getMessage());finish();}},350);}
    void begin(){try{
        SharedPreferences selection=a.getSharedPreferences(Pets.PREFS,0);for(String key:SELECTION_KEYS)if(selection.contains(key))savedSelection.put(key,selection.getAll().get(key));savedScene=Pets.scene;savedOverrideUntil=Pets.state.overrideUntil;savedOverrideIndex=Pets.state.overrideIndex;selectionSaved=true;int bird=-1;JSONArray catalog=Pets.catalog(a);for(int i=0;i<catalog.length();i++)if(catalog.optJSONObject(i).optString("id").equals("bird-pandora")){bird=i;break;}if(bird<0)throw new IllegalStateException("Charlie absent");
        prefs=SceneSettings.prefs(a,"bird-pandora");for(String key:KEYS)if(prefs.contains(key))saved.put(key,prefs.getAll().get(key));SharedPreferences.Editor e=prefs.edit();for(String key:KEYS)e.remove(key);e.apply();clean=new HashMap<>(prefs.getAll());a.select(bird);readyDeadline=SystemClock.elapsedRealtime()+5000;later(this::baseline);
    }catch(Throwable e){record("setup",false,e.getClass().getSimpleName());finish();}}
    float[] matrix(){float[] values=new float[9];stage.pag.matrix().getValues(values);return values;}
    boolean near(float x,float y){return Math.abs(x-y)<.002f;}
    void baseline(){
        if(a.preview.pag.getComposition()==null||a.preview.getWidth()<=0||a.preview.loaded.isEmpty()){if(SystemClock.elapsedRealtime()<readyDeadline){later(this::baseline);return;}throw new IllegalStateException("Charlie PAG/preview did not become ready");}
        stage=a.preview;original=(ViewGroup)a.previewCard.getParent();path=stage.loaded;playRevision=Pets.playRevision;initial=matrix();
        CoverGeometry.Placement p=CoverGeometry.focused(stage.getWidth(),stage.getHeight(),stage.pag.getComposition().width(),stage.pag.getComposition().height(),PetEnvelopes.get(a,"bird-pandora",path),stage.previewCameraRight,a.getSharedPreferences(Pets.PREFS,0).getFloat("cameraSafeFraction",CoverGeometry.CAMERA_FRACTION));
        record("default_clock_exact_legacy_matrix",stage.backdrop.clockEnabled()&&near(p.scale,initial[0])&&near(p.x,initial[2])&&near(p.y,initial[5]),"Actual PAGView matrix and app clock; existing focused placement");
        record("open_editor",a.layoutButton.performClick()&&a.layoutDialog!=null,"Actual selected-pet button");later(this::clockless);
    }
    void clockless(){record("reuse_existing_stage",stage==a.previewCard.stage&&a.previewCard.getParent()!=original,"One existing virtual cover reparented into dialog");RadioButton b=a.layoutDialog.findViewById(101);if(b!=null)b.performClick();boolean selected=b!=null&&b.isChecked()&&b.getParent() instanceof RadioGroup&&((RadioGroup)b.getParent()).getCheckedRadioButtonId()==101&&!stage.backdrop.clockEnabled();record("clockless_mode_button",selected,"Actual radio-button event selected checkedId101 and clockless preview draft");later(()->{
        large=matrix();record("clockless_larger_rendered",!stage.backdrop.clockEnabled()&&large[0]>initial[0]*1.15f,"Actual Charlie PAGView matrix scale increased; clock disabled");record("clockless_releases_digit_assets",!stage.backdrop.clockLoaded&&stage.backdrop.font==null&&stage.backdrop.digits[0]==null,"Backdrop draw retained donor background but released clock resources");record("draft_keeps_saved_mode",!PetLayout.read(a,Pets.current(a)).clockless&&clean.equals(prefs.getAll()),"No global override or saved settings during draft");
        record("manual_scale_accessibility",progress("Масштаб питомца",50),"Native SeekBar ACTION_SET_PROGRESS");record("manual_x_accessibility",progress("Положение питомца по горизонтали",30),"Native SeekBar ACTION_SET_PROGRESS");record("manual_y_accessibility",progress("Положение питомца по вертикали",21),"Native SeekBar ACTION_SET_PROGRESS");later(this::manual);
    });}
    boolean progress(String label,float progress){View v=find(a.layoutDialog.getWindow().getDecorView(),label);if(v==null)return false;Bundle args=new Bundle();args.putFloat(AccessibilityNodeInfo.ACTION_ARGUMENT_PROGRESS_VALUE,progress);return v.performAccessibilityAction(AccessibilityNodeInfo.AccessibilityAction.ACTION_SET_PROGRESS.getId(),args);}
    View find(View v,String label){if(label.equals(v.getContentDescription()))return v;if(v instanceof ViewGroup){ViewGroup g=(ViewGroup)v;for(int i=0;i<g.getChildCount();i++){View child=find(g.getChildAt(i),label);if(child!=null)return child;}}return null;}
    void manual(){float[] m=matrix();record("manual_adjustments_rendered",near(large[0]*1.10f,m[0])&&!near(large[2],m[2])&&!near(large[5],m[5]),"Actual source matrix reflects scale/X/Y");record("draft_no_preference_writes",clean.equals(prefs.getAll()),"All selected-pet preferences unchanged");record("layout_does_not_replay_scene",path.equals(stage.loaded)&&playRevision==Pets.playRevision,"No path load or playback revision change");a.layoutDialog.getButton(-2).performClick();later(this::cancelled);}
    void cancelled(){float[] m=matrix();record("cancel_restores_preview_and_parent",a.previewCard.getParent()==original&&stage.backdrop.clockEnabled()&&near(initial[0],m[0])&&near(initial[2],m[2])&&near(initial[5],m[5])&&clean.equals(prefs.getAll()),"Draft discarded; legacy stage returned to Main");a.layoutButton.performClick();((RadioButton)a.layoutDialog.findViewById(101)).performClick();progress("Масштаб питомца",50);progress("Положение питомца по горизонтали",30);a.layoutDialog.getButton(-1).performClick();later(this::applied);}
    void applied(){PetLayoutProfile p=PetLayout.read(a,Pets.current(a));record("apply_saves_selected_pet_mode",p.clockless&&near(p.scale,1.10f)&&near(p.x,.05f)&&near(p.y,0),"One explicit Apply saves mode and current profile");PetLayoutProfile clock=PetLayout.read(prefs,false);record("per_mode_clock_profile_preserved",clock.scale==1&&clock.x==0&&clock.y==0,"Other mode retains automatic legacy profile");a.layoutButton.performClick();View reset=a.layoutDialog.getWindow().getDecorView().findViewWithTag("pet-layout-reset");record("automatic_reset_button",reset!=null&&reset.performClick(),"Actual reset button");a.layoutDialog.getButton(-1).performClick();later(()->{PetLayoutProfile resetProfile=PetLayout.read(a,Pets.current(a));record("reset_selected_mode_removes_manual_keys",resetProfile.clockless&&resetProfile.scale==1&&resetProfile.x==0&&resetProfile.y==0&&!prefs.contains("petLargeScale")&&!prefs.contains("petLargeX")&&!prefs.contains("petLargeY"),"Reset clears only selected mode adjustments on Apply");finish();});}
    private static void restoreKeys(SharedPreferences prefs,String[] keys,Map<String,Object> values){SharedPreferences.Editor e=prefs.edit();for(String key:keys){e.remove(key);Object v=values.get(key);if(v instanceof Boolean)e.putBoolean(key,(Boolean)v);else if(v instanceof Float)e.putFloat(key,(Float)v);else if(v instanceof Integer)e.putInt(key,(Integer)v);else if(v instanceof Long)e.putLong(key,(Long)v);else if(v instanceof String)e.putString(key,(String)v);}e.apply();}
    private static boolean sameKeys(SharedPreferences prefs,String[] keys,Map<String,Object> values){for(String key:keys)if(values.containsKey(key)?!Objects.equals(values.get(key),prefs.getAll().get(key)):prefs.contains(key))return false;return true;}
    void finish(){if(ended)return;ended=true;handler.removeCallbacksAndMessages(null);try{if(a.layoutDialog!=null)a.layoutDialog.dismiss();boolean restored=true;if(prefs!=null){restoreKeys(prefs,KEYS,saved);restored=sameKeys(prefs,KEYS,saved);}if(selectionSaved){SharedPreferences selection=a.getSharedPreferences(Pets.PREFS,0);restoreKeys(selection,SELECTION_KEYS,savedSelection);Pets.scene=savedScene;Pets.state.overrideUntil=savedOverrideUntil;Pets.state.overrideIndex=savedOverrideIndex;a.preview.reload();a.refreshSelection();a.sendBroadcast(new android.content.Intent(Pets.EVENT).setPackage(a.getPackageName()));restored&=sameKeys(selection,SELECTION_KEYS,savedSelection)&&Pets.scene==savedScene&&Pets.state.overrideUntil==savedOverrideUntil&&Pets.state.overrideIndex==savedOverrideIndex;}record("test_layout_preferences_restored",restored,"Original layout keys, selection key presence, scene and override restored");}catch(Throwable e){record("restore_error",false,e.getClass().getSimpleName());}
        new Thread(()->{try{Pets.write(a,"pet-layout-qa.json",new JSONObject().put("apkSha256",Qa.binarySha(a)).put("environment","Android emulator; no physical camera/HyperOS claim").put("tested",results.length()).put("failed",failed).put("results",results).put("skipped",new JSONArray()).toString(2));}catch(Exception ignored){}finally{running=false;}},"pet-layout-qa-report").start();
    }
}
