package org.flippets.app;

import android.service.wallpaper.WallpaperService;
import android.os.*;
import android.view.SurfaceHolder;
import org.libpag.*;

/** Native PAG rendering into the surface assigned by Android's wallpaper manager. */
public class PetWallpaper extends WallpaperService {
    public Engine onCreateEngine(){return new PetEngine();}
    class PetEngine extends Engine implements android.hardware.SensorEventListener {
        final Handler handler=new Handler(Looper.getMainLooper());
        PAGPlayer player;PAGSurface surface;android.media.MediaPlayer video;String loaded="";long started,lastBattery,lastMinute=-1,lastPlayRevision=-1;double lastProgress=-1;boolean visible,ready;
        PAGImageLayer compositionLayer;PAGImage compositionImage;android.graphics.Bitmap compositionBitmap,compositionSpare;long compositionStamp=-1;boolean gravityRegistered;int cameraRight;
        final CompositionRenderer compositionRenderer=new CompositionRenderer(PetWallpaper.this);
        PAGImageLayer foregroundLayer;PAGImage foregroundImage;android.graphics.Bitmap foregroundBitmap;PhotoLayer photoLayer,frontLayer;long backgroundUpdated;
        PAGImageLayer background;PAGImage backgroundImage;android.graphics.Bitmap backgroundBitmap;PetBackdrop backdrop;
        final android.hardware.SensorManager sensors=(android.hardware.SensorManager)getSystemService(SENSOR_SERVICE);
        final Runnable frame=new Runnable(){public void run(){if(!visible||!ready)return;
            if(SystemClock.elapsedRealtime()-lastBattery>5000){Pets.battery(PetWallpaper.this);lastBattery=SystemClock.elapsedRealtime();}org.json.JSONObject selected=Pets.current(PetWallpaper.this);updateGravity(selected.optString("name").equals("Flowing glitter"));if(selected.optString("kind").equals("composition")){
                String key="@"+selected.optString("id");int w=getSurfaceHolder().getSurfaceFrame().width(),h=getSurfaceHolder().getSurfaceFrame().height();if(w<=0||h<=0){handler.postDelayed(this,100);return;}
                if(!key.equals(loaded)||player==null){releaseMedia();surface=PAGSurface.FromSurface(getSurfaceHolder().getSurface());player=new PAGPlayer();player.setSurface(surface);PAGComposition composition=PAGComposition.Make(w,h);compositionLayer=PAGImageLayer.Make(w,h,60000000L);compositionStamp=-1;composition.addLayer(compositionLayer);player.setComposition(composition);loaded=key;}
                String type=selected.optString("renderer");boolean still=type.equals("signature")||type.equals("paper")||type.equals("calendar")||type.equals("photo")||(type.equals("stretch")&&SystemClock.elapsedRealtime()-compositionRenderer.touchTime>2200);long stamp=System.currentTimeMillis()/60000^getSharedPreferences(Pets.PREFS,0).getLong("changeRevision",0);
                if(still&&stamp==compositionStamp){handler.postDelayed(this,1000);return;}
                float down=Math.min(1,1536f/Math.max(w,h));int bw=Math.max(1,Math.round(w*down)),bh=Math.max(1,Math.round(h*down));android.graphics.Bitmap bitmap=compositionSpare;if(bitmap==null||bitmap.getWidth()!=bw||bitmap.getHeight()!=bh){if(bitmap!=null)bitmap.recycle();bitmap=android.graphics.Bitmap.createBitmap(bw,bh,android.graphics.Bitmap.Config.ARGB_8888);}compositionRenderer.cameraRight=Math.round(cameraRight*down);compositionRenderer.draw(new android.graphics.Canvas(bitmap),bw,bh,selected,System.currentTimeMillis(),SystemClock.elapsedRealtime());PAGImage image=PAGImage.FromBitmap(bitmap);compositionLayer.setImage(image);if(compositionImage!=null)compositionImage.release();compositionSpare=compositionBitmap;compositionImage=image;compositionBitmap=bitmap;compositionStamp=stamp;player.flush();handler.postDelayed(this,still?1000:1000/Math.min(15,FlipPetsApp.frameRate(PetWallpaper.this)));return;
            }String path=Pets.path(PetWallpaper.this,Pets.stageIndex(PetWallpaper.this));
            if(path.isEmpty())path=Pets.path(PetWallpaper.this,0);
            if(!path.equals(loaded)){
                releaseMedia();loaded="";
                if(path.endsWith(".mp4")){final String videoPath=path;final android.media.MediaPlayer v=new android.media.MediaPlayer();video=v;try(android.content.res.AssetFileDescriptor fd=getAssets().openFd(path)){v.setDataSource(fd.getFileDescriptor(),fd.getStartOffset(),fd.getLength());v.setSurface(getSurfaceHolder().getSurface());v.setVolume(0,0);v.setLooping(true);v.setVideoScalingMode(android.media.MediaPlayer.VIDEO_SCALING_MODE_SCALE_TO_FIT_WITH_CROPPING);v.setOnErrorListener((m,what,extra)->{AppLog.event(PetWallpaper.this,"WALLPAPER_VIDEO_ERROR",what+"/"+extra+" "+videoPath);return true;});v.setOnPreparedListener(m->{if(video==m&&visible)m.start();});v.prepareAsync();loaded=path;}catch(Exception e){releaseMedia();AppLog.error(PetWallpaper.this,"WALLPAPER_VIDEO_LOAD",e);}}
                else{PAGFile f=PAGFile.Load(getAssets(),path);if(f!=null){int w=getSurfaceHolder().getSurfaceFrame().width(),h=getSurfaceHolder().getSurfaceFrame().height();if(w<=0||h<=0){handler.postDelayed(this,100);return;}surface=PAGSurface.FromSurface(getSurfaceHolder().getSurface());player=new PAGPlayer();player.setSurface(surface);player.setScaleMode(PAGScaleMode.LetterBox);player.setMaxFrameRate(FlipPetsApp.frameRate(PetWallpaper.this));
                    PAGComposition composition=PAGComposition.Make(w,h);background=PAGImageLayer.Make(w,h,f.duration());updateBackground(w,h);composition.addLayer(background);
                    float areaH=PetStage.renderHeight(w,h),areaW=w/(float)h<1.55f?areaH*976/596:w,scale=Math.min(areaW/f.width(),areaH/f.height());android.graphics.Matrix matrix=new android.graphics.Matrix();matrix.setScale(scale,scale);matrix.postTranslate(w-areaW+w/336f+(areaW-f.width()*scale)/2,h-areaH+4*h/213f+(areaH-f.height()*scale)/2);f.setMatrix(matrix);composition.addLayer(f);if(selected.optString("name").equals("Flowing glitter")){foregroundLayer=PAGImageLayer.Make(w,h,f.duration());composition.addLayer(foregroundLayer);updateBackground(w,h);}
                    player.setComposition(composition);loaded=path;started=SystemClock.elapsedRealtime();}}
            }
            if(player!=null){
                player.setMaxFrameRate(FlipPetsApp.frameRate(PetWallpaper.this));
                boolean dirty=System.currentTimeMillis()/60000!=lastMinute||(selected.optString("name").equals("Flowing glitter")&&SystemClock.elapsedRealtime()-backgroundUpdated>1000);
                if(dirty)updateBackground(getSurfaceHolder().getSurfaceFrame().width(),getSurfaceHolder().getSurfaceFrame().height());
                if(lastPlayRevision!=Pets.playRevision){lastPlayRevision=Pets.playRevision;started=SystemClock.elapsedRealtime();lastProgress=-1;}
                long duration=player.duration();
                boolean repeat=android.provider.Settings.Global.getFloat(getContentResolver(),"animator_duration_scale",1f)!=0&&PlaybackPolicy.repeats(selected.optString("id"),selected.optString("kind"),Pets.stageIndex(PetWallpaper.this),getSharedPreferences(Pets.PREFS,0).getBoolean("calmPets",false));
                if(duration>0){long elapsed=(SystemClock.elapsedRealtime()-started)*1000L;double progress=repeat?(elapsed%duration)/(double)duration:Math.min(1,elapsed/(double)duration);if(progress!=lastProgress||dirty){player.setProgress(progress);player.flush();lastProgress=progress;}}
            }
            handler.postDelayed(this,video==null&&lastProgress<1?1000/FlipPetsApp.frameRate(PetWallpaper.this):500);
        }};
        public void onApplyWindowInsets(android.view.WindowInsets insets){super.onApplyWindowInsets(insets);cameraRight=0;android.view.DisplayCutout cutout=insets.getDisplayCutout();if(cutout!=null)for(android.graphics.Rect r:cutout.getBoundingRects())if(r.left==0)cameraRight=Math.max(cameraRight,r.right);}
        public void onCreate(SurfaceHolder holder){super.onCreate(holder);setTouchEventsEnabled(true);}
        public void onSurfaceCreated(SurfaceHolder holder){super.onSurfaceCreated(holder);ready=true;handler.removeCallbacks(frame);if(visible)handler.post(frame);}
        public void onSurfaceChanged(SurfaceHolder h,int format,int width,int height){super.onSurfaceChanged(h,format,width,height);if(player!=null){releaseMedia();loaded="";}handler.removeCallbacks(frame);if(visible&&ready)handler.post(frame);}
        public void onVisibilityChanged(boolean shown){AppLog.event(PetWallpaper.this,"WALLPAPER_VISIBLE",Boolean.toString(shown));visible=shown;handler.removeCallbacks(frame);sensors.unregisterListener(this);if(shown&&checkSelfPermission(android.Manifest.permission.ACTIVITY_RECOGNITION)==android.content.pm.PackageManager.PERMISSION_GRANTED){android.hardware.Sensor sensor=sensors.getDefaultSensor(android.hardware.Sensor.TYPE_STEP_DETECTOR);if(sensor!=null)sensors.registerListener(this,sensor,android.hardware.SensorManager.SENSOR_DELAY_NORMAL);}gravityRegistered=false;if(shown)updateGravity(Pets.current(PetWallpaper.this).optString("name").equals("Flowing glitter"));if(!shown){releaseMedia();loaded="";compositionRenderer.release();if(photoLayer!=null)photoLayer.release();if(frontLayer!=null)frontLayer.release();if(backdrop!=null)backdrop.release();}if(shown)handler.post(frame);}
        void updateGravity(boolean wanted){if(wanted==gravityRegistered)return;android.hardware.Sensor sensor=sensors.getDefaultSensor(android.hardware.Sensor.TYPE_ACCELEROMETER);if(sensor!=null){if(wanted)sensors.registerListener(this,sensor,android.hardware.SensorManager.SENSOR_DELAY_UI);else sensors.unregisterListener(this,sensor);}gravityRegistered=wanted;}
        public void onSensorChanged(android.hardware.SensorEvent event){if(event.sensor.getType()==android.hardware.Sensor.TYPE_STEP_DETECTOR){Pets.state.sensorStep(event.timestamp,SystemClock.elapsedRealtime());StepStore.step(PetWallpaper.this,event.timestamp);}else if(event.sensor.getType()==android.hardware.Sensor.TYPE_ACCELEROMETER){Pets.tiltX=Pets.tiltX*.85f+event.values[0]/9.81f*.15f;Pets.tiltY=Pets.tiltY*.85f+event.values[1]/9.81f*.15f;}}
        public void onAccuracyChanged(android.hardware.Sensor sensor,int accuracy){}
        public void onTouchEvent(android.view.MotionEvent e){super.onTouchEvent(e);if(e.getAction()==android.view.MotionEvent.ACTION_UP){if(Pets.current(PetWallpaper.this).optString("kind").equals("composition")){android.graphics.Rect bounds=getSurfaceHolder().getSurfaceFrame();compositionStamp=-1;compositionRenderer.touch(e.getX()/Math.max(1,bounds.width()),e.getY()/Math.max(1,bounds.height()),SystemClock.elapsedRealtime());}else if(Pets.current(PetWallpaper.this).optString("kind").equals("reactive"))Pets.override(PetWallpaper.this,12+(int)(SystemClock.elapsedRealtime()%3),4500);else {org.json.JSONObject clips=Pets.current(PetWallpaper.this).optJSONObject("clips");if(clips!=null&&clips.length()>0)Pets.choose(PetWallpaper.this,(Pets.scene+1)%clips.length());}}}
        void updateBackground(int w,int h){if(background==null||w<=0||h<=0)return;android.graphics.Bitmap bitmap=android.graphics.Bitmap.createBitmap(w,h,android.graphics.Bitmap.Config.ARGB_8888);android.graphics.Canvas canvas=new android.graphics.Canvas(bitmap);org.json.JSONObject pet=Pets.current(PetWallpaper.this);android.graphics.Paint paint=new android.graphics.Paint();paint.setShader(new android.graphics.LinearGradient(0,0,0,h,color(pet.optString("gradientFrom","#444E70")),color(pet.optString("gradientTo","#647D98")),android.graphics.Shader.TileMode.CLAMP));canvas.drawRect(0,0,w,h,paint);if(pet.optString("name").equals("Flowing glitter")){if(photoLayer==null)photoLayer=new PhotoLayer(PetWallpaper.this,false);photoLayer.layout(0,0,w,h);photoLayer.draw(canvas);}
            if(backdrop==null)backdrop=new PetBackdrop(PetWallpaper.this,true);backdrop.layout(0,0,w,h);backdrop.draw(canvas);PAGImage image=PAGImage.FromBitmap(bitmap);background.setImage(image);if(backgroundImage!=null)backgroundImage.release();if(backgroundBitmap!=null)backgroundBitmap.recycle();backgroundImage=image;backgroundBitmap=bitmap;lastMinute=System.currentTimeMillis()/60000;backgroundUpdated=SystemClock.elapsedRealtime();if(foregroundLayer!=null){android.graphics.Bitmap front=android.graphics.Bitmap.createBitmap(w,h,android.graphics.Bitmap.Config.ARGB_8888);if(frontLayer==null)frontLayer=new PhotoLayer(PetWallpaper.this,true);frontLayer.layout(0,0,w,h);frontLayer.draw(new android.graphics.Canvas(front));PAGImage imageFront=PAGImage.FromBitmap(front);foregroundLayer.setImage(imageFront);if(foregroundImage!=null)foregroundImage.release();if(foregroundBitmap!=null)foregroundBitmap.recycle();foregroundImage=imageFront;foregroundBitmap=front;}}
        int color(String value){try{return android.graphics.Color.parseColor(value);}catch(Exception e){return 0xff444e70;}}
        void releaseMedia(){lastProgress=-1;lastPlayRevision=Pets.playRevision;if(video!=null){video.release();video=null;}if(player!=null){player.release();player=null;}if(surface!=null){surface.release();surface=null;}compositionStamp=-1;compositionLayer=null;if(compositionSpare!=null){compositionSpare.recycle();compositionSpare=null;}if(compositionImage!=null){compositionImage.release();compositionImage=null;}if(compositionBitmap!=null){compositionBitmap.recycle();compositionBitmap=null;}foregroundLayer=null;if(foregroundImage!=null){foregroundImage.release();foregroundImage=null;}if(foregroundBitmap!=null){foregroundBitmap.recycle();foregroundBitmap=null;}background=null;if(backgroundImage!=null){backgroundImage.release();backgroundImage=null;}if(backgroundBitmap!=null){backgroundBitmap.recycle();backgroundBitmap=null;}lastMinute=-1;}
        public void onSurfaceDestroyed(SurfaceHolder holder){ready=false;handler.removeCallbacks(frame);releaseMedia();loaded="";super.onSurfaceDestroyed(holder);}
        public void onDestroy(){handler.removeCallbacks(frame);sensors.unregisterListener(this);releaseMedia();compositionRenderer.release();if(photoLayer!=null)photoLayer.release();if(frontLayer!=null)frontLayer.release();super.onDestroy();}
    }
}
